delivery/backend/config/routes.rb
Abc::Backend::Engine.routes.draw do
  root to: 'base#index'

  resources :pages
end

delivery/backend/app/controllers/abc/backend/base_controller.rb
module Abc
  module Backend
    class BaseController < ApplicationController
      def index
      end
    end
  end
end

delivery/backend/app/controllers/abc/backend/pages_controller.rb
require 'conductors/pages/fetches_pages'
require 'conductors/pages/accepts_page_form'
require 'abc/presentation'
require 'abc/html/page_presenter'

module Abc
  module Backend
    class PagesController < ApplicationController
      include Abc::Presentation

      def index
        present Conductors::Pages::FetchesPages.new(params, :repositories => repositories).call
      end

      def new
        # Maybe?
        # @page = Entities::Pages::Page.new
      end

      def create
        Conductors::Pages::AcceptsPageForm.new(params, :repositories => repositories).call
        redirect_to pages_path
      end

      protected
      def repositories
        @repositories ||= {:page => Adapters::Persistence::Repositories::Page.new}
      end

      def presenters
        @presenters ||= {:page => Html::PagePresenter}
      end
    end
  end
end

delivery/backend/app/views/abc/backend/base/index.html.haml
%section
  Welcome to Afterburner CMS backend.

%aside
  More functionality coming soon.

delivery/backend/app/views/abc/backend/pages/index.html.haml
%h2 Pages
- @data.pages.each do |page|
  = link_to page.title, '#'
= link_to "New Page", new_page_path

delivery/backend/app/views/abc/backend/pages/new.html.haml
%h2 New Page

= form_tag pages_path do
  %label{ for: 'title' } Title
  = text_field_tag :title
  %label{ for: 'body' } Body
  = text_area_tag :body
  = submit_tag "Create Page"

delivery/backend/app/views/layouts/abc/application.html.haml
!!! 5
%html
  %head
    %title= "Afterburner CMS"
    %meta{ :content => "", :name => "description" }
    %meta{ :content => "", :name => "author" }
    =stylesheet_link_tag "application"
  %body
    %header
      %h1= "Company Name"

    %section
      =yield

    %footer
      %p= "Copyright #{Time.zone.now.year}"